# path to dataset, need modification if necessary
DATASET:
  PATH: /home/liuwang/liuwang_data/documents/datasets/seg/2024-CVPR-Agriculture-Vision/supervised/Agriculture-Vision-2021

# path to save the model, need modification if necessary
EXPERIMENT:
  SAVER:
    DIRPATH: ./models/
  LOGGER:
    TRACKING_URI: "file:./mlruns/0527-FPN-efficientnet-b5-AcwBceJcd"
  NAME: "results/0527-FPN-efficientnet-b5-AcwBceJcd"
# The trainer setting, each node in our cluster has 4 2080Ti GPU.
# This model requires 4 GPUs in total, so set GPUS=4
TRAINER:
  MAX_STEPS: 160000
  GPUS: 2
  ACCELERATOR: ddp
  SYNC_BATCHNORM: true

DATALOADER:
  BATCH_SIZE:
    TRAIN: 8
    TEST: 4
    VAL: 4
  INCLUDE_VALID: true

LOSS:
  VERSION: MLACWJaccardLoss

MODEL:
  ENCODER: efficientnet-b5
  VERSION: FPN

SEED: 2021
